[package]
name = "simple-encrypt"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]

[dev-dependencies]

[profile.release]
lto = true

[lints.rust]
missing_docs = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(docsrs_dep)'] }
#unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "warn"
unused_qualifications = "warn"

[lints.clippy]
#alloc_instead_of_core = "warn"
allow_attributes = "warn"
allow_attributes_without_reason = "warn"
doc_markdown = "warn"
manual_let_else = "warn"
match_same_arms = "warn"
#needless_lifetimes = "allow"
nonstandard_macro_braces = "warn"
print_stderr = "warn"
print_stdout = "warn"
ptr_as_ptr = "warn"
ptr_cast_constness = "warn"
redundant_closure_for_method_calls = "warn"
redundant_else = "warn"
ref_as_ptr = "warn"
semicolon_if_nothing_returned = "warn"
#std_instead_of_core = "allow"
#std_instead_of_alloc = "warn"
#too_long_first_doc_paragraph = "allow"
#too_many_arguments = "allow"
#type_complexity = "allow"
undocumented_unsafe_blocks = "warn"
unwrap_or_default = "warn"
